version: 0.2

phases:
  install:
    commands:
      - cd backend
      - npm install --force
  build:
    commands:
      - echo "Zipping up Lambda code..."
      - zip -r ../backend-deploy.zip .
      - echo "Deploying Lambda code to AWS..."
      - aws lambda update-function-code --function-name interviewprep --zip-file fileb://../backend-deploy.zip --region us-east-1

artifacts:
  files:
    - backend-deploy.zip
